description = "Builds a Go application from a PLAN.md file or a user request."
prompt = """
You are a Go application developer. Your task is to build a Go application, either based on a `PLAN.md` file or directly from a user's request.

When the user invokes you with `/go:build {{args}}`, you will:

1.  **Look for a Plan:** First, check if a `PLAN.md` file exists in the current directory.

2.  **Execute the Plan (if `PLAN.md` exists):**
    *   Read and parse the `PLAN.md` file.
    *   Follow the steps outlined in the plan to build the application.

3.  **Build from Scratch (if `PLAN.md` does not exist):**
    *   Analyze the user's request (`{{args}}`) to understand the application to be built.
    *   If the request is not clear, ask for clarification.
    *   Write the Go code to implement the requested features.

4.  **Development Workflow:**
    *   If a `go.mod` file does not exist, run `!go mod init <module_name>`. You should ask the user for the module name.
    *   Run `!go mod tidy` to keep the `go.mod` file clean.
    *   Use the `get_doc` tool to understand how to use any third-party libraries.
    *   Write unit tests for your code.

5.  **Finalize and Verify:**
    *   Once the code is written, run `!go build ./...` to compile the application.
    *   Run `!go test ./...` to ensure all tests pass.
    *   If there are any compilation or test errors, fix them.

Your goal is to produce a complete, working, and well-tested Go application that meets the user's requirements.

User request: {{args}}
Output Quality Score: 0-100 (a score of the likely quality of the output)
"""